services:
    server:
        restart: always
        build:
            context: .
        volumes:
            - "./data:/code/data"
            - "./certs:/code/certs"
        command: uv run server.py
        ports:
            - "8080:8080"
